<a href="https://colab.research.google.com/github/sonnylewis1/ML-Zoomcamp/blob/main/ML_Zoomcamp_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**QUESTION 1**

In [2]:
np.__version__

'1.19.5'

**QUESTION 2**

In [3]:
pd.__version__

'1.1.5'

In [21]:
url = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
df = pd.read_csv(url)

In [22]:
df.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

**QUESTION 3**

In [23]:
df[df['Make'] == 'BMW']['MSRP'].mean()

61546.76347305389

**QUESTION 4**

In [24]:
df[df['Year'] >= 2015]['Engine HP'].isnull().sum()

51

**QUESTION 5**

In [25]:
mean_hp_before = df['Engine HP'].mean()
print(round(mean_hp_before))

249


In [26]:
df['Engine HP'] = df['Engine HP'].fillna(mean_hp_before)

In [27]:
mean_hp_after = df['Engine HP'].mean()
print(round(mean_hp_after))

249


**QUESTION 6**

In [33]:
df_rollsroyce = df[df['Make'] == 'Rolls-Royce'][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()
df_rollsroyce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [36]:
X = df_rollsroyce.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [38]:
XTX = X.T.dot(X)

In [39]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [42]:
XTX_inv = np.linalg.inv(XTX)

In [44]:
XTX_inv.sum()

0.032212320677486125

**QUESTION 7**

In [47]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [48]:
w = (XTX_inv.dot(X.T)).dot(y)

In [49]:
w

array([ 0.19989598, 31.02612262, 31.65378877])